// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: InitialProject

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Frwdbuttonpress(lv_event_t * e);
void Switchpressed(lv_event_t * e);
void PswdtxtPressed(lv_event_t * e);
void Loginbtn(lv_event_t * e);
void Bckbtnpress(lv_event_t * e);
void Slidervalue(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
