// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: InitialProject

#include "ui.h"

void Frwdbuttonpress(lv_event_t * e)
{
	// Your code here
}

void Switchpressed(lv_event_t * e)
{
	// Your code here
}

void PswdtxtPressed(lv_event_t * e)
{
	// Your code here
}

void Loginbtn(lv_event_t * e)
{
	// Your code here
}

void Bckbtnpress(lv_event_t * e)
{
	// Your code here
}

void Slidervalue(lv_event_t * e)
{
	// Your code here
}
