// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: InitialProject

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern void ui_event_fswdbtn(lv_event_t * e);
extern lv_obj_t * ui_fswdbtn;
extern lv_obj_t * ui_Label6;
extern void ui_event_switchbtn(lv_event_t * e);
extern lv_obj_t * ui_switchbtn;
extern void ui_event_pswdtext(lv_event_t * e);
extern lv_obj_t * ui_pswdtext;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_rndmtxt;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_pswdlabel;
extern void ui_event_loginbutton(lv_event_t * e);
extern lv_obj_t * ui_loginbutton;
extern lv_obj_t * ui_login_button_txt2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

