// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: InitialProject

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_backbtn = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_slider = NULL;
lv_obj_t * ui_percentgvalue = NULL;
// event funtions
void ui_event_backbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        Bckbtnpress(e);
    }
}

void ui_event_slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_percentgvalue, target, "", "%");
        _ui_basic_set_property(ui_percentgvalue, _UI_BASIC_PROPERTY_POSITION_X,  0);
        Slidervalue(e);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_add_flag(ui_Screen2, LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Screen2, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_Screen2, LV_DIR_HOR);
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x100101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backbtn = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_backbtn, 182);
    lv_obj_set_height(ui_backbtn, 84);
    lv_obj_set_x(ui_backbtn, -295);
    lv_obj_set_y(ui_backbtn, 183);
    lv_obj_set_align(ui_backbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backbtn, lv_color_hex(0xCC8116), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_backbtn);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "BACK ");
    lv_label_set_recolor(ui_Label3, "true");

    ui_slider = lv_slider_create(ui_Screen2);
    lv_slider_set_value(ui_slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_slider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_slider, 272);
    lv_obj_set_height(ui_slider, 34);
    lv_obj_set_x(ui_slider, -49);
    lv_obj_set_y(ui_slider, -74);
    lv_obj_set_align(ui_slider, LV_ALIGN_CENTER);

    ui_percentgvalue = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_percentgvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_percentgvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_percentgvalue, 52);
    lv_obj_set_y(ui_percentgvalue, -106);
    lv_obj_set_align(ui_percentgvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_percentgvalue, "0%");
    lv_obj_set_style_text_color(ui_percentgvalue, lv_color_hex(0xBB8715), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_percentgvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_percentgvalue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backbtn, ui_event_backbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_slider, ui_event_slider, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_backbtn = NULL;
    ui_Label3 = NULL;
    ui_slider = NULL;
    ui_percentgvalue = NULL;

}
