// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: InitialProject

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_fswdbtn = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_switchbtn = NULL;
lv_obj_t * ui_pswdtext = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_rndmtxt = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_pswdlabel = NULL;
lv_obj_t * ui_loginbutton = NULL;
lv_obj_t * ui_login_button_txt2 = NULL;
// event funtions
void ui_event_fswdbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
        Frwdbuttonpress(e);
    }
}

void ui_event_switchbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Switchpressed(e);
    }
}

void ui_event_pswdtext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_pswdtext);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        PswdtxtPressed(e);
    }
}

void ui_event_loginbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Loginbtn(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_add_state(ui_Screen1, LV_STATE_CHECKED);       /// States
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x0B0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fswdbtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_fswdbtn, 187);
    lv_obj_set_height(ui_fswdbtn, 74);
    lv_obj_set_x(ui_fswdbtn, 238);
    lv_obj_set_y(ui_fswdbtn, 181);
    lv_obj_set_align(ui_fswdbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fswdbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_fswdbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_fswdbtn, lv_color_hex(0xE67112), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fswdbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_fswdbtn);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -1);
    lv_obj_set_y(ui_Label6, 3);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "FORWARD");

    ui_switchbtn = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_switchbtn, 78);
    lv_obj_set_height(ui_switchbtn, 34);
    lv_obj_set_x(ui_switchbtn, -206);
    lv_obj_set_y(ui_switchbtn, -111);
    lv_obj_set_align(ui_switchbtn, LV_ALIGN_CENTER);

    ui_pswdtext = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_pswdtext, 298);
    lv_obj_set_height(ui_pswdtext, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_x(ui_pswdtext, 165);
    lv_obj_set_y(ui_pswdtext, -27);
    lv_obj_set_align(ui_pswdtext, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_pswdtext, "Placeholder...");
    lv_textarea_set_one_line(ui_pswdtext, true);
    lv_textarea_set_password_mode(ui_pswdtext, true);

    ui_Button3 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 772);
    lv_obj_set_y(ui_Button3, 120);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rndmtxt = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_rndmtxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rndmtxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rndmtxt, 126);
    lv_obj_set_y(ui_rndmtxt, -121);
    lv_obj_set_align(ui_rndmtxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rndmtxt, "RANDOM VALUE");
    lv_obj_set_style_text_color(ui_rndmtxt, lv_color_hex(0x92F688), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rndmtxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rndmtxt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard1, 447);
    lv_obj_set_height(ui_Keyboard1, 183);
    lv_obj_set_x(ui_Keyboard1, -149);
    lv_obj_set_y(ui_Keyboard1, 133);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_pswdlabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_pswdlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pswdlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pswdlabel, -115);
    lv_obj_set_y(ui_pswdlabel, -28);
    lv_obj_set_align(ui_pswdlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pswdlabel, "VALID/INVALID");
    lv_obj_set_style_text_color(ui_pswdlabel, lv_color_hex(0xF8ED1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pswdlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pswdlabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loginbutton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_loginbutton, 100);
    lv_obj_set_height(ui_loginbutton, 50);
    lv_obj_set_x(ui_loginbutton, 181);
    lv_obj_set_y(ui_loginbutton, 61);
    lv_obj_set_align(ui_loginbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loginbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_loginbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_login_button_txt2 = lv_label_create(ui_loginbutton);
    lv_obj_set_width(ui_login_button_txt2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_login_button_txt2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_login_button_txt2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_login_button_txt2, "LOGIN");

    lv_obj_add_event_cb(ui_fswdbtn, ui_event_fswdbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switchbtn, ui_event_switchbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pswdtext, ui_event_pswdtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_loginbutton, ui_event_loginbutton, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_fswdbtn = NULL;
    ui_Label6 = NULL;
    ui_switchbtn = NULL;
    ui_pswdtext = NULL;
    ui_Button3 = NULL;
    ui_rndmtxt = NULL;
    ui_Keyboard1 = NULL;
    ui_pswdlabel = NULL;
    ui_loginbutton = NULL;
    ui_login_button_txt2 = NULL;

}
